-- Dialeto: MariaDB

CREATE DATABASE IF NOT EXISTS banco_de_dados;

USE banco_de_dados;

CREATE TABLE IF NOT EXISTS Aluno (
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS Responsavel (
    Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS Parentesco (
    IdResponsavel INT NOT NULL,
    IdAluno INT NOT NULL,
    Parentesco VARCHAR(64) NOT NULL
);

ALTER TABLE Parentesco ADD FOREIGN KEY (IdResponsavel) REFERENCES Responsavel(Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Parentesco ADD FOREIGN KEY (IdAluno) REFERENCES Aluno(Id) ON DELETE CASCADE ON UPDATE CASCADE;
```